<?php
// /academy/resources/protected_viewer/celpip_reading.php?part=celpip_reading_pt1
// Protected slide-deck viewer: renders one slide at a time via canvas (image
// slides) or a styled card (text slides), never exposing a direct file URL --
// each slide is fetched through serve_slide.php, which re-checks auth per
// request. Includes a per-viewer watermark (student name/email/timestamp)
// and best-effort deterrents (blocked right-click/selection/print/save
// shortcuts, disabled image dragging). None of this can stop a screenshot or
// screen recording -- no browser API allows a page to block those -- so the
// watermark is the real protection here: it survives a screenshot and
// identifies whoever took it.

require_once dirname(dirname(__DIR__)) . '/bootstrap.php';
require_once INCLUDES_PATH . '/tier_access.php';
require_once INCLUDES_PATH . '/protected_reading_resources.php';

if (!isset($_SESSION['user_id'])) {
    header("Location: " . ACADEMY_URL . "edu_hub_registration.php?message=Please+login+to+access+resources");
    exit();
}

$part = $_GET['part'] ?? '';
if (!isset(PROTECTED_READING_RESOURCES[$part])) {
    die("Resource not found.");
}
$resource = PROTECTED_READING_RESOURCES[$part];

if (!can_access($resource['min_tier'])) {
    require_once INCLUDES_PATH . '/mobile_header.php';
    require_once INCLUDES_PATH . '/navbar.php';
    echo '<main class="main-wrapper" style="padding:3rem 1.5rem;display:flex;justify-content:center;">';
    render_upgrade_prompt($resource['min_tier'], $resource['title']);
    echo '</main>';
    require_once INCLUDES_PATH . '/navbar_scripts.php';
    exit;
}

$manifestPath = ACADEMY_ROOT . '/protected_resources/' . $part . '/manifest.json';
$manifest = file_exists($manifestPath) ? json_decode(file_get_contents($manifestPath), true) : ['slides' => []];
$totalSlides = count($manifest['slides']);

$studentName  = trim(($_SESSION['user_firstname'] ?? '') . ' ' . ($_SESSION['user_lastname'] ?? ''));
$studentEmail = $_SESSION['user_email'] ?? '';
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?= htmlspecialchars($resource['title']) ?> | EduHub</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
<?php include INCLUDES_PATH . '/navbar_styles.php'; ?>
<style>
    .viewer-wrapper { padding: 1.5rem; max-width: 1100px; margin: 0 auto; }
    .viewer-title { font-weight: 700; color: #1f2937; margin-bottom: 1rem; }

    .viewer-stage {
        position: relative;
        background: #111827;
        border-radius: 14px;
        overflow: hidden;
        box-shadow: 0 10px 40px rgba(0,0,0,.25);
        aspect-ratio: 16 / 9;
        display: flex;
        align-items: center;
        justify-content: center;
        user-select: none;
        -webkit-user-select: none;
    }
    .viewer-stage img {
        max-width: 100%;
        max-height: 100%;
        width: 100%;
        height: 100%;
        object-fit: contain;
        pointer-events: none; /* blocks drag-to-save / right-click-on-image-specifically */
        -webkit-user-drag: none;
    }
    .text-slide-card {
        width: 100%;
        height: 100%;
        background: #fff;
        padding: 3rem 3.5rem;
        display: flex;
        flex-direction: column;
        justify-content: center;
        gap: .75rem;
        overflow-y: auto;
    }
    .text-slide-card .label { font-weight: 800; font-size: .8rem; letter-spacing: .08em; text-transform: uppercase; color: #667eea; margin-top: .5rem; }
    .text-slide-card .body { font-size: 1.15rem; color: #1f2937; line-height: 1.6; }

    .stage-loading { color: rgba(255,255,255,.6); font-size: .9rem; }

    /* Tiled watermark, generated by JS, sits above the slide but below controls */
    .watermark-layer {
        position: absolute;
        inset: 0;
        pointer-events: none;
        overflow: hidden;
        z-index: 5;
    }
    .watermark-tile {
        position: absolute;
        color: rgba(255,255,255,.16);
        font-size: .72rem;
        font-weight: 600;
        white-space: nowrap;
        transform: rotate(-28deg);
    }

    .viewer-controls {
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin-top: 1rem;
        gap: 1rem;
    }
    .nav-btn {
        background: #1f2937; color: #fff; border: none; border-radius: 8px;
        padding: .6rem 1.1rem; font-weight: 600; font-size: .9rem; cursor: pointer;
        display: flex; align-items: center; gap: .4rem;
    }
    .nav-btn:disabled { opacity: .35; cursor: not-allowed; }
    .nav-btn:not(:disabled):hover { background: #374151; }
    .slide-counter { font-size: .9rem; color: #4b5563; font-weight: 600; }

    .protect-notice { font-size: .78rem; color: #9ca3af; text-align: center; margin-top: .75rem; }
</style>
</head>
<body oncontextmenu="return false;">

<?php include INCLUDES_PATH . '/mobile_header.php'; ?>
<?php include INCLUDES_PATH . '/navbar.php'; ?>

<main class="main-wrapper" style="flex:1;">
    <div class="viewer-wrapper">
        <h1 class="viewer-title h4"><?= htmlspecialchars($resource['title']) ?></h1>

        <div class="viewer-stage" id="stage" data-part="<?= htmlspecialchars($part) ?>" data-total="<?= (int)$totalSlides ?>">
            <div class="stage-loading" id="stageLoading">Loading…</div>
            <div class="watermark-layer" id="watermarkLayer"></div>
        </div>

        <div class="viewer-controls">
            <button class="nav-btn" id="prevBtn"><i class="bi bi-chevron-left"></i> Previous</button>
            <span class="slide-counter" id="slideCounter">Slide 1 of <?= (int)$totalSlides ?></span>
            <button class="nav-btn" id="nextBtn">Next <i class="bi bi-chevron-right"></i></button>
        </div>

        <p class="protect-notice">
            <i class="bi bi-shield-lock me-1"></i>
            This material is licensed to <?= htmlspecialchars($studentName ?: 'you') ?> for personal study only. Do not copy, download, or redistribute.
        </p>
    </div>
</main>

<?php include INCLUDES_PATH . '/navbar_scripts.php'; ?>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script>
const PART = <?= json_encode($part) ?>;
const TOTAL = <?= (int)$totalSlides ?>;
const STUDENT_LABEL = <?= json_encode(trim(($studentName ?: 'Student') . '  ·  ' . $studentEmail)) ?>;

let current = 1;
const stage = document.getElementById('stage');
const loading = document.getElementById('stageLoading');
const watermarkLayer = document.getElementById('watermarkLayer');
const counter = document.getElementById('slideCounter');
const prevBtn = document.getElementById('prevBtn');
const nextBtn = document.getElementById('nextBtn');

function buildWatermark() {
    watermarkLayer.innerHTML = '';
    const stamp = STUDENT_LABEL + '  ·  ' + new Date().toLocaleString();
    const cols = 4, rows = 4;
    for (let r = 0; r < rows; r++) {
        for (let c = 0; c < cols; c++) {
            const el = document.createElement('div');
            el.className = 'watermark-tile';
            el.textContent = stamp;
            el.style.left = (c * (100 / cols) + 2) + '%';
            el.style.top = (r * (100 / rows) + 6) + '%';
            watermarkLayer.appendChild(el);
        }
    }
}

async function loadSlide(n) {
    loading.style.display = 'block';
    loading.textContent = 'Loading…';

    // Clear previous slide content (but keep the watermark layer node)
    Array.from(stage.children).forEach(child => {
        if (child !== watermarkLayer && child !== loading) child.remove();
    });

    try {
        const res = await fetch(`serve_slide.php?part=${encodeURIComponent(PART)}&n=${n}`);
        if (!res.ok) throw new Error('Failed to load slide (' + res.status + ')');
        const contentType = res.headers.get('Content-Type') || '';

        if (contentType.includes('application/json')) {
            const data = await res.json();
            const card = document.createElement('div');
            card.className = 'text-slide-card';
            (data.lines || []).forEach(line => {
                const isLabel = line === 'Question' || line === 'Answer';
                const el = document.createElement('div');
                el.className = isLabel ? 'label' : 'body';
                el.textContent = line;
                card.appendChild(el);
            });
            stage.insertBefore(card, watermarkLayer);
        } else {
            const blob = await res.blob();
            const url = URL.createObjectURL(blob);
            const img = document.createElement('img');
            img.src = url;
            img.draggable = false;
            img.alt = 'Slide ' + n;
            stage.insertBefore(img, watermarkLayer);
        }
        loading.style.display = 'none';
    } catch (err) {
        loading.textContent = 'Could not load this slide. Please refresh.';
    }

    counter.textContent = `Slide ${n} of ${TOTAL}`;
    prevBtn.disabled = n <= 1;
    nextBtn.disabled = n >= TOTAL;
}

prevBtn.addEventListener('click', () => { if (current > 1) { current--; loadSlide(current); } });
nextBtn.addEventListener('click', () => { if (current < TOTAL) { current++; loadSlide(current); } });
document.addEventListener('keydown', (e) => {
    if (e.key === 'ArrowLeft') prevBtn.click();
    if (e.key === 'ArrowRight') nextBtn.click();
});

// Best-effort deterrents. None of these can block an OS-level screenshot or
// screen recording -- no browser API exposes that -- so treat this purely as
// friction against casual copying, not real protection. The watermark above
// is what actually matters if something does leak.
document.addEventListener('contextmenu', e => e.preventDefault());
document.addEventListener('selectstart', e => e.preventDefault());
document.addEventListener('dragstart', e => e.preventDefault());
document.addEventListener('keydown', (e) => {
    const k = e.key.toLowerCase();
    const mod = e.ctrlKey || e.metaKey;
    if (mod && ['p','s','u'].includes(k)) e.preventDefault();
    if (k === 'printscreen') { /* not blockable; no-op */ }
});

buildWatermark();
loadSlide(current);
</script>

</body>
</html>
