-- Migration 041 — Seed a cleaned Word of the Day list based on the provided vocabulary notes
-- Phase 1, Step 4 of the Vocabulary Banks feature.
-- Run on LOCAL first, then LIVE.
-- INSERT IGNORE: safe to re-run — skips rows that already exist (headword has UNIQUE KEY).

INSERT IGNORE INTO vocabulary_words
    (headword, phonetic, word_class, cefr_level, is_awl, definition, secondary_definitions, synonyms, antonyms, collocations, word_family, sort_order)
VALUES

('absentmindedly',
 '/ˌæb.səntˈmaɪn.dɪd.li/',
 'adverb', 'B2', 0,
 'In a way that shows a lack of attention or awareness of what is happening around you.',
 NULL,
 'carelessly, inattentively, distractedly, vaguely, unconsciously',
 'attentively, carefully, deliberately',
 'absentmindedly staring, absentmindedly muttering, absentmindedly browsing',
 'absentminded (adj.) · absentmindedness (n.)',
 1),

('articulate',
 '/ɑːˈtɪk.jə.lət/',
 'verb', 'B2', 1,
 'To express an idea or feeling clearly and effectively.',
 'To speak in a clear and fluent way.',
 'express, explain, communicate, convey, state',
 'muddle, confuse, conceal',
 'articulate a view, articulate clearly, articulate the problem, articulate an opinion',
 'articulate (v.) · articulation (n.) · articulate (adj.)',
 2),

('charming',
 '/ˈtʃɑː.mɪŋ/',
 'adjective', 'B2', 0,
 'Very pleasant or attractive in a way that makes people like you.',
 NULL,
 'pleasant, delightful, attractive, engaging, appealing',
 'unpleasant, dull, repulsive',
 'charming smile, charming personality, charming host, charming manner',
 'charm (n./v.) · charmed (adj.) · charmingly (adv.)',
 3),

('complex',
 '/kəmˈpleks/',
 'adjective', 'B2', 1,
 'Made of many interrelated parts; difficult to understand because of this.',
 'A building or set of buildings with related functions; also a psychological state of inner conflict.',
 'complicated, intricate, involved, sophisticated, difficult',
 'simple, straightforward, easy',
 'complex issue, complex system, complex relationship, complex process',
 'complex (adj./n.) · complexity (n.) · complexly (adv.)',
 4),

('cosmopolitan',
 '/ˌkɒz.məˈpɒl.ɪ.tən/',
 'adjective', 'C1', 0,
 'Including people from many different countries or cultures; worldly and international in style.',
 NULL,
 'international, global, diverse, multicultural, worldly',
 'local, provincial, narrow',
 'cosmopolitan city, cosmopolitan society, cosmopolitan culture',
 'cosmopolitan (adj.) · cosmopolitanism (n.)',
 5),

('decadent',
 '/ˈdek.ə.dənt/',
 'adjective', 'C1', 0,
 'Characterised by excessive self-indulgence, luxury, or moral decline.',
 NULL,
 'luxurious, indulgent, extravagant, excessive, opulent',
 'modest, restrained, disciplined',
 'decadent lifestyle, decadent culture, decadent luxury, decadent pleasures',
 'decadent (adj.) · decadence (n.)',
 6),

('disquiet',
 '/dɪsˈkwaɪ.ət/',
 'noun', 'C1', 0,
 'A feeling of anxiety, worry, or unease.',
 NULL,
 'unease, anxiety, concern, unrest, apprehension',
 'calm, ease, reassurance',
 'deep disquiet, public disquiet, growing disquiet, silent disquiet',
 'disquiet (n.) · disquieting (adj.)',
 7),

('eccentric',
 '/ɪkˈsen.trɪk/',
 'adjective', 'B2', 0,
 'Behaving in a way that is unusual or not typical, often in an interesting way.',
 'A person with unusual or unconventional behaviour.',
 'odd, quirky, unconventional, unusual, unusual',
 'conventional, normal, typical',
 'eccentric artist, eccentric style, eccentric behaviour, eccentric ideas',
 'eccentric (adj./n.) · eccentricity (n.)',
 8),

('envious',
 '/ˈen.vi.əs/',
 'adjective', 'B2', 0,
 'Feeling resentment because someone else has something desirable that you want.',
 NULL,
 'jealous, resentful, covetous, green with envy',
 'content, satisfied, happy',
 'envious of a friend, envious stare, envious glance, envious remarks',
 'envious (adj.) · envy (n./v.)',
 9),

('evocative',
 '/ɪˈvɒk.ə.tɪv/',
 'adjective', 'C1', 0,
 'Creating a strong image, feeling, or memory in the mind.',
 NULL,
 'moving, expressive, memorable, suggestive, atmospheric',
 'plain, dull, unremarkable',
 'evocative language, evocative imagery, evocative music, evocative scene',
 'evocative (adj.) · evoke (v.) · evocation (n.)',
 10),

('flagrant',
 '/ˈfleɪɡ.rənt/',
 'adjective', 'C1', 0,
 'Clearly wrong, shocking, or obvious in a way that is impossible to ignore.',
 NULL,
 'obvious, blatant, glaring, evident, scandalous',
 'subtle, hidden, minor',
 'flagrant abuse, flagrant violation, flagrant disregard, flagrant hypocrisy',
 'flagrant (adj.) · flagrantly (adv.)',
 11),

('gentrification',
 '/ˌdʒen.trɪ.fɪˈkeɪ.ʃən/',
 'noun', 'C1', 0,
 'The process by which a poorer area becomes more fashionable and expensive as wealthier people move in.',
 NULL,
 'urban renewal, redevelopment, rising property prices, neighbourhood change',
 NULL,
 'gentrification of the city, resist gentrification, fear of gentrification',
 'gentrify (v.) · gentrified (adj.)',
 12),

('grumbling',
 '/ˈɡrʌm.bəl.ɪŋ/',
 'noun', 'B1', 0,
 'The act of complaining in a quiet, irritated way.',
 NULL,
 'complaint, moan, protest, muttering, dissatisfaction',
 'praise, approval, satisfaction',
 'grumbling voice, grumbling workers, constant grumbling, low grumbling',
 'grumble (v.) · grumbler (n.)',
 13),

('kerfuffle',
 '/ˈkɜː.fʌf.əl/',
 'noun', 'B2', 0,
 'A state of confusion, fuss, or commotion.',
 NULL,
 'commotion, fuss, uproar, disorder, confusion',
 'order, calm, peace',
 'a kerfuffle over the plan, create a kerfuffle, minor kerfuffle',
 'kerfuffle (n.)',
 14),

('lackadaisical',
 '/ˌlæk.əˈdeɪ.zɪ.kəl/',
 'adjective', 'C1', 0,
 'Lacking enthusiasm, energy, or determination.',
 NULL,
 'apathetic, lazy, sluggish, indifferent, listless',
 'enthusiastic, energetic, motivated',
 'lackadaisical attitude, lackadaisical response, lackadaisical effort',
 'lackadaisical (adj.) · lackadaisicality (n.)',
 15),

('nuance',
 '/ˈnjuː.ɑːns/',
 'noun', 'B2', 1,
 'A subtle difference in meaning, expression, or tone.',
 NULL,
 'subtlety, distinction, shade, fine point, detail',
 'obviousness, bluntness',
 'nuance of meaning, cultural nuance, subtle nuance, important nuance',
 'nuanced (adj.) · nuancedly (adv.)',
 16),

('outstrip',
 '/aʊtˈstrɪp/',
 'verb', 'C1', 0,
 'To exceed or go beyond something in amount, speed, or level.',
 NULL,
 'surpass, exceed, outdo, overshadow, beat',
 'fall behind, lag behind, trail',
 'outstrip demand, outstrip expectations, outstrip rivals, outstrip growth',
 'outstrip (v.) · outstripping (n.)',
 17),

('pester',
 '/ˈpes.tər/',
 'verb', 'B2', 0,
 'To trouble or annoy someone repeatedly, especially with repeated requests or questions.',
 NULL,
 'annoy, harass, badger, bother, nag',
 'comfort, reassure, soothe',
 'pester the teacher, pester someone for answers, pester repeatedly',
 'pester (v.) · pestering (n./adj.)',
 18),

('precarious',
 '/prɪˈkeə.ri.əs/',
 'adjective', 'B2', 1,
 'Not securely held or in a position of possible danger or loss.',
 NULL,
 'unstable, risky, uncertain, insecure, fragile',
 'secure, stable, safe',
 'precarious situation, precarious job, precarious balance, precarious future',
 'precarious (adj.) · precariousness (n.)',
 19),

('predecessor',
 '/ˈpred.ɪ.ses.ər/',
 'noun', 'C1', 1,
 'A person or thing that came before another in a role, position, or time.',
 NULL,
 'forerunner, ancestor, earlier version, previous model, precursor',
 'successor, follower, replacement',
 'predecessor in the role, predecessor company, previous predecessor',
 'predecessor (n.) · predecessor model',
 20),

('quintessential',
 '/ˌkwɪn.tɪˈsen.ʃəl/',
 'adjective', 'C1', 0,
 'Representing the most perfect or typical example of something.',
 NULL,
 'typical, perfect, classic, ideal, archetypal',
 'atypical, unusual, imperfect',
 'quintessential example, quintessential style, quintessential city, quintessential quality',
 'quintessential (adj.) · quintessentially (adv.)',
 21),

('reiterate',
 '/riːˈɪt.ə.reɪt/',
 'verb', 'C1', 1,
 'To say or do something again, often to emphasise it or make it clearer.',
 NULL,
 'repeat, restate, emphasise, reassert, reiterate',
 'omit, hide, suppress',
 'reiterate the point, reiterate the message, reiterate the warning',
 'reiterate (v.) · reiteration (n.)',
 22),

('relevant',
 '/ˈrel.ə.vənt/',
 'adjective', 'B2', 1,
 'Closely connected to the matter being considered or discussed.',
 NULL,
 'appropriate, connected, related, suitable, applicable',
 'irrelevant, unrelated, inappropriate',
 'relevant evidence, relevant details, highly relevant, remain relevant',
 'relevant (adj.) · relevance (n.)',
 23),

('rug pull',
 '/rʌɡ pʊl/',
 'phrase', 'C1', 0,
 'A sudden abandonment of a project or investment scheme after people have already committed money or trust.',
 NULL,
 'scam, betrayal, collapse, fraud, deception',
 'honesty, trust, reliability',
 'a rug pull scandal, avoid a rug pull, investors hit by a rug pull',
 'rug pull (phrase)',
 24),

('self-deprecation',
 '/ˌself.dep.rəˈkeɪ.ʃən/',
 'noun', 'B2', 0,
 'The act of making fun of yourself in a light or modest way.',
 NULL,
 'humility, mockery, satire, teasing, understatement',
 'boasting, arrogance, self-praise',
 'self-deprecation in humour, gentle self-deprecation, playful self-deprecation',
 'self-deprecating (adj.)',
 25),

('stiff-upper lip',
 '/stɪf ˈʌp.ər lɪp/',
 'phrase', 'B2', 0,
 'A tendency to hide emotions and remain calm, controlled, and unemotional in difficult situations.',
 NULL,
 'reserve, composure, control, restraint, stoicism',
 'emotional openness, self-expression',
 'keep a stiff-upper lip, maintain a stiff-upper lip, classic stiff-upper lip',
 'stiff-upper lip (phrase)',
 26),

('tantalising',
 '/ˈtæn.təl.aɪ.zɪŋ/',
 'adjective', 'C1', 0,
 'Very tempting or exciting because it is attractive but just out of reach.',
 NULL,
 'tempting, alluring, inviting, exciting, intriguing',
 'uninteresting, dull, unappealing',
 'tantalising offer, tantalising prospect, tantalising idea, tantalising possibility',
 'tantalise (v.) · tantalisingly (adv.)',
 27),

('unconventional',
 '/ʌn.kənˈven.ʃən.əl/',
 'adjective', 'B2', 1,
 'Not based on or following traditional ideas, methods, or styles.',
 NULL,
 'unusual, original, innovative, alternative, non-standard',
 'conventional, traditional, standard',
 'unconventional approach, unconventional method, unconventional idea',
 'unconventional (adj.) · unconventionality (n.)',
 28),

('vivid',
 '/ˈvɪv.ɪd/',
 'adjective', 'B2', 1,
 'Producing strong, clear, and detailed images or feelings in the mind.',
 NULL,
 'clear, bright, striking, graphic, lively',
 'vague, dull, faint',
 'vivid description, vivid memory, vivid colour, vivid imagination',
 'vivid (adj.) · vividly (adv.) · vividness (n.)',
 29),

('whimsical',
 '/ˈwɪm.zɪ.kəl/',
 'adjective', 'C1', 0,
 'Playfully imaginative or unusual in a way that is charming and light-hearted.',
 NULL,
 'playful, fanciful, quirky, imaginative, fanciful',
 'serious, practical, conventional',
 'whimsical design, whimsical story, whimsical style, whimsical idea',
 'whimsical (adj.) · whimsy (n.)',
 30);
