-- Migration 041 — Seed first 30 vocabulary words (Academic Word List Sublist 1 + high-frequency test words)
-- Phase 1, Step 4 of the Vocabulary Banks feature.
-- Run on LOCAL first, then LIVE.
-- INSERT IGNORE: safe to re-run — skips rows that already exist (headword has UNIQUE KEY).

INSERT IGNORE INTO vocabulary_words
    (headword, phonetic, word_class, cefr_level, is_awl, definition, secondary_definitions, synonyms, antonyms, collocations, word_family, sort_order)
VALUES

-- 1
('analyse',
 '/ˈæn.ə.laɪz/',
 'verb', 'C1', 1,
 'To examine something in detail in order to understand it better or draw conclusions from it.',
 NULL,
 'examine, evaluate, investigate, study, inspect',
 'ignore, overlook, neglect',
 'analyse data, analyse results, analyse trends, critically analyse, analyse in detail',
 'analysis (n.) · analyst (n.) · analytical (adj.) · analytically (adv.) · analyse (v.)',
 1),

-- 2
('approach',
 '/əˈprəʊtʃ/',
 'noun', 'B2', 1,
 'A way of dealing with a situation or problem.',
 'To move closer to something or someone; to speak to someone about something for the first time.',
 'method, strategy, technique, way, system',
 NULL,
 'take an approach, different approach, practical approach, adopt an approach, new approach to',
 'approach (n.) · approach (v.) · approachable (adj.)',
 2),

-- 3
('assess',
 '/əˈses/',
 'verb', 'B2', 1,
 'To judge or decide the amount, value, quality, or importance of something.',
 NULL,
 'evaluate, judge, measure, appraise, gauge',
 'ignore, overlook, dismiss',
 'assess the impact, assess risk, assess skills, formally assess, assess the situation',
 'assess (v.) · assessment (n.) · assessor (n.) · reassess (v.)',
 3),

-- 4
('benefit',
 '/ˈben.ɪ.fɪt/',
 'noun', 'B1', 1,
 'An advantage or something that has a positive effect on a person or situation.',
 'To receive an advantage from something.',
 'advantage, gain, reward, asset, merit',
 'disadvantage, drawback, harm, loss',
 'major benefit, potential benefit, benefit from, mutual benefit, financial benefit',
 'benefit (n.) · benefit (v.) · beneficial (adj.) · beneficially (adv.) · beneficiary (n.)',
 4),

-- 5
('concept',
 '/ˈkɒn.sept/',
 'noun', 'B2', 1,
 'An idea or principle that is connected with something abstract.',
 NULL,
 'idea, notion, principle, theory, thought',
 'reality, fact, concrete thing',
 'key concept, abstract concept, basic concept, grasp a concept, introduce a concept',
 'concept (n.) · conceptual (adj.) · conceptually (adv.) · conceptualise (v.)',
 5),

-- 6
('context',
 '/ˈkɒn.tekst/',
 'noun', 'B2', 1,
 'The situation, events, or information related to and helping to explain something else.',
 NULL,
 'setting, background, circumstances, framework, environment',
 NULL,
 'in context, historical context, social context, within the context of, out of context',
 'context (n.) · contextual (adj.) · contextualise (v.) · contextually (adv.)',
 6),

-- 7
('contribute',
 '/kənˈtrɪb.juːt/',
 'verb', 'B2', 0,
 'To give something — time, money, or ideas — in order to help achieve or produce something.',
 NULL,
 'add, donate, provide, give, supply',
 'take, withhold, detract',
 'contribute to, significantly contribute, contribute ideas, contribute to the debate',
 'contribute (v.) · contribution (n.) · contributor (n.) · contributory (adj.)',
 7),

-- 8
('crucial',
 '/ˈkruː.ʃəl/',
 'adjective', 'B2', 0,
 'Extremely important because many other things depend on it.',
 NULL,
 'vital, essential, critical, key, decisive',
 'unimportant, trivial, minor, irrelevant',
 'crucial role, crucial factor, absolutely crucial, crucial decision, prove crucial',
 'crucial (adj.) · crucially (adv.)',
 8),

-- 9
('demonstrate',
 '/ˈdem.ən.streɪt/',
 'verb', 'B2', 0,
 'To show or prove something clearly through evidence, action, or argument.',
 'To march or gather publicly to show support for or opposition to something.',
 'show, prove, illustrate, exhibit, display',
 'conceal, hide, disprove',
 'demonstrate ability, demonstrate clearly, demonstrate the importance of, clearly demonstrate',
 'demonstrate (v.) · demonstration (n.) · demonstrator (n.) · demonstrable (adj.) · demonstrably (adv.)',
 9),

-- 10
('environment',
 '/ɪnˈvaɪ.rən.mənt/',
 'noun', 'B1', 1,
 'The natural world, including land, water, air, plants, and animals; or the conditions that affect behaviour and development.',
 NULL,
 'surroundings, habitat, ecosystem, setting, atmosphere',
 NULL,
 'natural environment, working environment, protect the environment, damage the environment, learning environment',
 'environment (n.) · environmental (adj.) · environmentally (adv.) · environmentalist (n.)',
 10),

-- 11
('establish',
 '/ɪˈstæb.lɪʃ/',
 'verb', 'B2', 1,
 'To start or create an organisation, system, or relationship intended to last a long time.',
 'To find out or prove the facts of a situation.',
 'found, set up, create, build, form',
 'abolish, dismantle, dissolve',
 'establish a business, establish links, establish a fact, well-established, establish guidelines',
 'establish (v.) · establishment (n.) · established (adj.)',
 11),

-- 12
('evaluate',
 '/ɪˈvæl.ju.eɪt/',
 'verb', 'B2', 0,
 'To judge or calculate the quality, importance, amount, or value of something.',
 NULL,
 'assess, judge, appraise, measure, rate',
 'ignore, overlook, disregard',
 'evaluate performance, evaluate evidence, critically evaluate, evaluate the effectiveness of',
 'evaluate (v.) · evaluation (n.) · evaluative (adj.)',
 12),

-- 13
('factor',
 '/ˈfæk.tər/',
 'noun', 'B2', 1,
 'One of the things that influences whether an event happens or the way something develops.',
 NULL,
 'element, aspect, component, consideration, influence',
 NULL,
 'key factor, contributing factor, risk factor, deciding factor, factor in',
 'factor (n.) · factor in (v.) · factorial (adj.)',
 13),

-- 14
('focus',
 '/ˈfəʊ.kəs/',
 'verb', 'B1', 0,
 'To give attention or effort to one particular subject or area rather than others.',
 'The main topic or point of interest; the state of being clear and sharp.',
 'concentrate, centre, target, direct, emphasise',
 'ignore, neglect, avoid, distract',
 'focus on, main focus, shift focus, lose focus, remain focused, bring into focus',
 'focus (n.) · focus (v.) · focused (adj.) · refocus (v.)',
 14),

-- 15
('identify',
 '/aɪˈden.tɪ.faɪ/',
 'verb', 'B2', 1,
 'To recognise or be able to name someone or something; to find or discover something.',
 NULL,
 'recognise, detect, pinpoint, spot, determine',
 'overlook, miss, confuse',
 'identify a problem, identify trends, clearly identify, identify with, identify the cause',
 'identify (v.) · identification (n.) · identity (n.) · identifiable (adj.) · identifiably (adv.)',
 15),

-- 16
('impact',
 '/ˈɪm.pækt/',
 'noun', 'B2', 0,
 'The strong effect or influence that something has on a situation or person.',
 'To have a strong effect on something.',
 'effect, influence, consequence, result, impression',
 NULL,
 'significant impact, have an impact on, negative impact, positive impact, measure the impact',
 'impact (n.) · impact (v.) · impactful (adj.)',
 16),

-- 17
('indicate',
 '/ˈɪn.dɪ.keɪt/',
 'verb', 'B2', 1,
 'To show, point to, or make something clear; to be a sign of something.',
 NULL,
 'show, suggest, point to, signal, imply',
 'conceal, hide, contradict',
 'indicate that, clearly indicate, indicate a trend, results indicate, strongly indicate',
 'indicate (v.) · indication (n.) · indicator (n.) · indicative (adj.)',
 17),

-- 18
('individual',
 '/ˌɪn.dɪˈvɪdʒ.u.əl/',
 'adjective', 'B1', 1,
 'Existing as a single, separate thing or person; relating to one person rather than a group.',
 'A single person considered separately from a group.',
 'single, separate, particular, personal, distinct',
 'collective, group, general, communal',
 'individual needs, individual approach, every individual, individual rights, individual differences',
 'individual (n./adj.) · individually (adv.) · individualism (n.) · individualise (v.)',
 18),

-- 19
('involve',
 '/ɪnˈvɒlv/',
 'verb', 'B1', 1,
 'To include someone or something as a necessary part of something.',
 NULL,
 'include, require, entail, contain, engage',
 'exclude, omit, avoid',
 'involve risk, actively involve, become involved in, involve a process, tasks involve',
 'involve (v.) · involvement (n.) · involved (adj.)',
 19),

-- 20
('issue',
 '/ˈɪʃ.uː/',
 'noun', 'B1', 1,
 'An important topic or problem that people are discussing or arguing about.',
 'To officially produce or provide something.',
 'problem, matter, topic, subject, concern',
 'solution, answer, resolution',
 'key issue, raise an issue, address an issue, current issue, major issue, social issue',
 'issue (n.) · issue (v.)',
 20),

-- 21
('maintain',
 '/meɪnˈteɪn/',
 'verb', 'B2', 0,
 'To keep something in its current state or at a particular level; to continue to have something.',
 'To state that you believe something to be true.',
 'keep, preserve, sustain, uphold, retain',
 'neglect, abandon, drop, lose',
 'maintain standards, maintain a balance, maintain contact, difficult to maintain, maintain order',
 'maintain (v.) · maintenance (n.) · maintainable (adj.)',
 21),

-- 22
('method',
 '/ˈmeθ.əd/',
 'noun', 'B1', 1,
 'A particular way of doing something, especially one that is planned or established.',
 NULL,
 'approach, technique, way, procedure, strategy',
 NULL,
 'teaching method, scientific method, effective method, traditional method, research method',
 'method (n.) · methodical (adj.) · methodically (adv.) · methodology (n.)',
 22),

-- 23
('policy',
 '/ˈpɒl.ɪ.si/',
 'noun', 'B2', 1,
 'A set of ideas or a plan of action agreed on by a government, business, or other organisation.',
 NULL,
 'plan, strategy, guidelines, regulations, approach',
 NULL,
 'government policy, implement a policy, education policy, foreign policy, economic policy',
 'policy (n.) · policymaker (n.)',
 23),

-- 24
('principle',
 '/ˈprɪn.sɪ.pəl/',
 'noun', 'B2', 1,
 'A basic rule or idea that explains how something works, or a moral rule guiding behaviour.',
 NULL,
 'rule, law, standard, guideline, value',
 NULL,
 'basic principle, fundamental principle, in principle, on principle, guiding principle',
 'principle (n.) · principled (adj.) · unprincipled (adj.)',
 24),

-- 25
('process',
 '/ˈprəʊ.ses/',
 'noun', 'B1', 1,
 'A series of actions or events that produce a result or bring about a change.',
 'To deal with official documents or information in a particular way.',
 'procedure, system, method, operation, series of steps',
 NULL,
 'decision-making process, lengthy process, go through a process, natural process, learning process',
 'process (n.) · process (v.) · processed (adj.)',
 25),

-- 26
('significant',
 '/sɪɡˈnɪf.ɪ.kənt/',
 'adjective', 'B2', 1,
 'Important or large enough to have an effect or to be noticed.',
 NULL,
 'important, considerable, substantial, notable, meaningful',
 'insignificant, minor, trivial, negligible',
 'significant increase, significant role, highly significant, statistically significant, significant impact',
 'significant (adj.) · significantly (adv.) · significance (n.) · signify (v.) · insignificant (adj.)',
 26),

-- 27
('structure',
 '/ˈstrʌk.tʃər/',
 'noun', 'B2', 1,
 'The way in which the parts of a system or object are arranged or organised.',
 'To organise or arrange something in a particular way.',
 'organisation, arrangement, framework, system, composition',
 'chaos, disorder, randomness',
 'social structure, clear structure, sentence structure, organisational structure, logical structure',
 'structure (n.) · structure (v.) · structural (adj.) · structurally (adv.) · restructure (v.)',
 27),

-- 28
('suggest',
 '/səˈdʒest/',
 'verb', 'A2', 0,
 'To mention an idea or plan for someone else to think about; to show that something is likely or possible.',
 NULL,
 'propose, recommend, advise, imply, indicate',
 'oppose, reject, refute',
 'suggest that, strongly suggest, evidence suggests, suggest an idea, suggest a reason',
 'suggest (v.) · suggestion (n.) · suggestive (adj.)',
 28),

-- 29
('therefore',
 '/ˈðeə.fɔːr/',
 'adverb', 'B1', 0,
 'For that reason; as a result of what has just been stated.',
 NULL,
 'consequently, thus, hence, as a result, for this reason',
 NULL,
 'it is therefore, therefore concluded, and therefore, therefore necessary, therefore important',
 'therefore (adv.) — no derivatives',
 29),

-- 30
('vary',
 '/ˈveər.i/',
 'verb', 'B1', 1,
 'To be different from other things of the same type, or to change in some way.',
 NULL,
 'differ, change, fluctuate, alternate, range',
 'stay the same, remain constant, be uniform',
 'vary widely, vary according to, vary considerably, results vary, prices vary',
 'vary (v.) · variety (n.) · various (adj.) · variable (n./adj.) · variation (n.) · varied (adj.)',
 30);
