from lib import *
L={}
L['Orientation & Diagnostic Assessment']=page(
 ["explain the four parts of IELTS Academic and how each is scored","take the diagnostic test and read your result honestly","set a target band and a weekly study rhythm for this course"],
 h("The test in one table"),
 table(["Part","Time","What you do","Marked by"],[
  ["Listening","about 30 minutes + 10 to transfer answers","4 recordings, 40 questions; you hear each recording once","Answer key (1 mark per question)"],
  ["Reading","60 minutes","3 long texts, 40 questions; no extra time to transfer","Answer key (1 mark per question)"],
  ["Writing","60 minutes","Task 1: describe a graph, chart, table, map or process (150+ words). Task 2: an essay (250+ words)","Trained examiners against 4 criteria; Task 2 counts twice as much as Task 1"],
  ["Speaking","11–14 minutes","A face-to-face interview in three parts, recorded","Trained examiner against 4 criteria"]]),
 p("Every part is reported as a band from 1 to 9 (half bands are possible). Your <strong>overall band</strong> is the average of the four, rounded to the nearest half band. Universities and immigration bodies usually name a minimum overall band and sometimes a minimum in each part, so know both numbers for your goal."),
 h("How the four Writing and Speaking criteria work"),
 p("You will hear four names again and again in this course. Learn them now."),
 table(["Writing","Speaking"],[
  ["Task Achievement (Task 1) / Task Response (Task 2): did you answer the question fully?","Fluency and Coherence: do you speak smoothly and logically?"],
  ["Coherence and Cohesion: is it organised and easy to follow?","Lexical Resource: how wide and how accurate is your vocabulary?"],
  ["Lexical Resource: range and accuracy of vocabulary","Grammatical Range and Accuracy: variety and control of structures"],
  ["Grammatical Range and Accuracy: variety and control of structures","Pronunciation: how easy are you to understand?"]]),
 h("Your diagnostic"),
 p("The diagnostic is a short, honest snapshot of where you start. It is <strong>not</strong> a pass or fail. The most useful thing you can do is take it under real conditions."),
 ol(["Find a quiet place, use headphones and put your phone away.","Do not look anything up. A wrong answer now tells us exactly what to teach you.","Finish in one sitting.","Afterwards, write down the two things that felt hardest. We will come back to them in Week 8."]),
 p('<a class="btn btn-primary" href="<?= ACADEMY_URL ?>resources/mock_tests/ielts_aca_diagnostic.php"><i class="bi bi-play-circle me-1"></i>Open the Academic diagnostic</a>'),
 h("Reading your result"),
 ul(["<strong>Listening and Reading</strong> are scored by the machine. Look at which question types you lost marks on, not only the total.","<strong>Writing</strong> is scored against the four criteria. A weak criterion is more useful to know than a single band.","A result is a starting point. Most learners move by half a band to one band over eight weeks when they follow the plan and practise every week."]),
 h("Set your target and your rhythm"),
 ul(["Write your target overall band and the minimum you need in each part.","Subtract your diagnostic from your target. That gap decides how much you must add each week.","Plan two class sessions a week, plus at least three short practice sessions of 20–30 minutes. Little and often beats one long weekend session."]),
 tip("Put your study times in your calendar today. A plan with a time attached gets done; a plan without one is a wish."),
 take("The test rewards steady, specific practice. Know your target, know your starting point, and let the next eight weeks close the gap one skill at a time."))
L['Writing Task Overview']=page(
 ["tell Task 1 and Task 2 apart and split your 60 minutes sensibly","name what examiners look for in each task","plan a response before writing a single sentence"],
 h("Two tasks, two jobs"),
 table(["","Task 1","Task 2"],[
  ["What it is","Describe visual information: a graph, chart, table, map or process","Write an essay giving your view on a topic"],
  ["Minimum length","150 words","250 words"],
  ["Time to spend","about 20 minutes","about 40 minutes"],
  ["Weight","one third of the Writing band","two thirds of the Writing band"],
  ["Your opinion?","Never. Report only what you can see.","Yes, if the question asks for it"]]),
 p("Task 2 counts twice as much as Task 1, so if time is tight, protect the 40 minutes for Task 2. A common plan is Task 1 first (20 minutes), then Task 2 (40 minutes). Some strong candidates do Task 2 first; choose one and stick with it in every practice."),
 h("What a Task 1 answer must contain"),
 ol(["<strong>Introduction:</strong> one or two sentences that say what the visual shows, in your own words.","<strong>Overview:</strong> two or three sentences that give the big picture: the biggest changes, the highest and lowest, the overall pattern. No numbers here. This is the paragraph that separates band 6 from band 7.","<strong>Detail paragraphs:</strong> the key figures and comparisons, grouped logically. You do not need to mention every number."]),
 warn("Do not give reasons or opinions in Task 1 (\"because people prefer...\"). The data cannot tell you why."),
 h("What a Task 2 answer must contain"),
 ol(["<strong>Introduction:</strong> paraphrase the question and state your position or your plan.","<strong>Two or three body paragraphs:</strong> one main idea each, explained and supported with an example.","<strong>Conclusion:</strong> restate your position in fresh words. Do not add new ideas."]),
 h("A two-minute plan is not wasted time"),
 p("Before you write, spend two minutes on paper. Task 1: what are the two or three main features? How will I group the details? Task 2: what is my position? What are my two main points and one example for each?"),
 ex("Sample plan for a Task 2 essay","<p>Question: <em>Some people think children should start school at 5, others at 7. Discuss both views and give your opinion.</em></p><p>Position: earlier is better if the school is play-based. Point 1: early social skills. Point 2: language development. View 2 (7): children are not ready, pressure. My opinion: start at 5 with a gentle programme.</p>"),
 tryit("Look at a Task 1 question you have seen before, or use any graph in a newspaper. In five minutes write:",["one sentence that says what the graph shows (introduction)","two sentences that give the overall pattern (overview)","the three figures you would definitely quote"],None),
 take("Two tasks, two jobs: describe accurately in Task 1, argue clearly in Task 2. Plan first, protect the time for Task 2, and never skip the overview."))
L['Trend Vocabulary & Paraphrasing']=page(
 ["describe upward, downward and stable trends with accurate verbs, nouns and adverbs","paraphrase the question in your introduction without changing its meaning","avoid the most common Task 1 vocabulary mistakes"],
 h("Verbs and nouns for change"),
 table(["Direction","Verb","Noun"],[
  ["Up","rise, increase, grow, climb, go up","a rise, an increase, growth, a climb"],
  ["Down","fall, decrease, decline, drop, go down","a fall, a decrease, a decline, a drop"],
  ["Stay the same","remain stable, stay constant, level off","a plateau"],
  ["Up then down","peak at ... then fall","a peak"],
  ["Down then up","hit a low of ... then recover","a low point / a trough"]]),
 h("Adjectives and adverbs for size and speed"),
 table(["How big / how fast","Adjective + noun","Verb + adverb"],[
  ["Big or fast","a sharp rise, a dramatic fall, a significant increase","rose sharply, fell dramatically, increased significantly"],
  ["Small or slow","a slight rise, a gradual decline","rose slightly, declined gradually"],
  ["Steady","a steady increase","increased steadily"]]),
 p("Use the two patterns to vary your sentences:"),
 ul(["Verb + adverb: <em>Sales <strong>rose sharply</strong> in 2015.</em>","There was + adjective + noun: <em>There was <strong>a sharp rise</strong> in sales in 2015.</em>"]),
 warn("<strong>Rise</strong> and <strong>fall</strong> have no object (\"sales rose\", never \"sales rose the price\"). <strong>Increase</strong> and <strong>decrease</strong> can be both: <em>The company increased prices.</em>"),
 h("Prepositions with numbers"),
 table(["Use","Example"],[
  ["<strong>to</strong> = where it ended","rose <strong>to</strong> 40%"],
  ["<strong>by</strong> = the size of the change","rose <strong>by</strong> 10%"],
  ["<strong>from ... to</strong>","rose <strong>from</strong> 30% <strong>to</strong> 40%"],
  ["<strong>at</strong> = a level or a peak","peaked <strong>at</strong> 40%, stood <strong>at</strong> 40%"]]),
 h("Paraphrasing the question"),
 p("Never copy the question into your introduction. Change the vocabulary and, where you can, the structure. Keep the meaning identical."),
 table(["Original","Paraphrase"],[
  ["The graph shows","The line graph illustrates / gives information about / compares"],
  ["the number of","the figures for / the amount of / how many"],
  ["between 2000 and 2010","over a ten-year period / from 2000 to 2010"],
  ["in three countries","in three different nations"],
  ["percentage","proportion / share"]]),
 ex("Question and paraphrase","<p><em>The graph below shows the percentage of households with internet access in three countries between 2000 and 2020.</em></p><p><strong>Paraphrase:</strong> The line graph compares the proportion of homes that were online in three nations over a twenty-year period.</p>"),
 tryit("Paraphrase each sentence.",["The chart shows the number of visitors to four museums in 2019.","The table gives information about the average price of houses in five cities.","The graph illustrates changes in the percentage of people who smoke."],
  ["The bar chart compares how many people went to four museums in 2019.","The table compares what a typical home cost in five cities.","The line graph shows how the proportion of smokers changed over time."]),
 take("Pick the verb, noun and adverb that match the size and speed of the change, get your prepositions exactly right, and change the question's words so the examiner sees your own vocabulary."))
L['Comparative Structures & TEE']=page(
 ["compare two or more items with a range of accurate comparative structures","build a detail paragraph with a topic sentence, evidence and explanation (TEE)","avoid the errors that keep Task 1 at band 5 or 6"],
 h("Comparing in Task 1"),
 p("Task 1 is full of comparisons: one year against another, one country against another, the highest against the lowest. Learn these structures and mix them."),
 table(["Structure","Example"],[
  ["Comparative adjective + than","Fuel prices were <strong>higher than</strong> food prices."],
  ["as ... as / not as ... as","Spending on travel was <strong>almost as high as</strong> spending on food."],
  ["twice / three times as ... as","Japan spent <strong>twice as much as</strong> Italy."],
  ["the most / the least","Rent was <strong>the largest</strong> expense; heating was <strong>the smallest</strong>."],
  ["While / Whereas / By contrast","<strong>Whereas</strong> exports rose, imports fell."],
  ["Similarly / In the same way","<strong>Similarly</strong>, the figure for women increased."],
  ["A greater / smaller proportion of ... than","A <strong>greater proportion of</strong> men than women worked full-time."]]),
 warn("Compare like with like. Write <em>the population of Tokyo was larger than <strong>that of</strong> Paris</em>, not <em>larger than Paris</em>."),
 h("TEE: the detail paragraph"),
 p("A good detail paragraph is not a list of numbers. Give it a shape:"),
 ul(["<strong>T – Topic sentence.</strong> Say what this paragraph is about: <em>Turning to the leisure categories, ...</em>","<strong>E – Evidence.</strong> Give the key figures that support it.","<strong>E – Explain / Compare.</strong> Say what the figures show by comparing them or naming the pattern."]),
 ex("One TEE paragraph","<p><strong>T</strong> Looking at the four cities, Lagos had by far the fastest growth. <strong>E</strong> Its population rose from 8 million in 1990 to 15 million in 2020. <strong>E</strong> That is nearly double, whereas the other three cities grew by less than 30%.</p>"),
 tryit("Write one sentence for each pair using the structure in brackets.",["Cars: 40% of journeys. Buses: 20% of journeys. (twice as ... as)","Men: 55%. Women: 45%. (a greater proportion ... than)","Coal fell. Solar rose. (whereas)"],
  ["Cars were used for twice as many journeys as buses.","A greater proportion of men than women were employed.","Coal use fell, whereas solar power rose."]),
 take("Vary your comparisons, compare like with like, and give every detail paragraph a topic, its evidence and a sentence that explains what the numbers mean."))
L['Map Description & Passive Voice']=page(
 ["describe how a place has changed between two maps","use the passive voice naturally for changes done to a place","organise a map answer so the overview is clear"],
 h("What map tasks ask for"),
 p("You are usually given two or three maps of the same place at different times, or a map now and a planned future map. You must describe <strong>what changed</strong> and <strong>what stayed the same</strong>. There are no numbers, so vocabulary and grammar carry the score."),
 h("Location language"),
 table(["Idea","Phrases"],[
  ["Where things are","in the north-east, to the west of, opposite, next to, between, along the river, at the entrance"],
  ["Things that appear","was built, was constructed, was added, appeared, a new ... was opened"],
  ["Things that disappear","was demolished, was knocked down, was removed, was cleared, was replaced by"],
  ["Things that change","was converted into, was extended, was enlarged, was relocated, was divided into"],
  ["Things that stay","remained unchanged, stayed the same, was not altered"]]),
 h("The passive, and why maps love it"),
 p("In map tasks the person who built the thing is not important, so the passive is natural: <em>A car park <strong>was built</strong> to the east of the school.</em> Form it with <strong>be + past participle</strong>, and match the tense to the time in the map."),
 table(["Time in the map","Passive form","Example"],[
  ["Past change (between two past maps)","was / were + past participle","The farmland <strong>was replaced</strong> by housing."],
  ["Future plan","will be + past participle","A bridge <strong>will be built</strong> across the river."],
  ["Something in the map now","is / are + past participle","The old factory <strong>is used</strong> as a museum."]]),
 warn("Do not use the passive for things that happen by themselves: write <em>The village grew</em>, not <em>The village was grown</em>."),
 h("Structure your answer"),
 ol(["<strong>Introduction:</strong> say what the maps show and the years.","<strong>Overview:</strong> the big picture: <em>The area changed from mainly farmland to a residential district, and transport links improved.</em>","<strong>Detail 1:</strong> the north and west, comparing the maps.","<strong>Detail 2:</strong> the south and east, comparing the maps."]),
 ex("Model sentences","<p>The two maps show how the town of Norbiton changed between 1990 and today.</p><p>Overall, the industrial area was largely replaced by housing and leisure facilities, and access to the site improved.</p>"),
 tryit("Rewrite each sentence in the passive.",["The council built a new road to the north.","They will remove the old warehouse.","The company turned the farm into a hotel."],
  ["A new road was built to the north.","The old warehouse will be removed.","The farm was turned into a hotel."]),
 take("Say what changed and where, use the passive for things built, removed or converted, and give an overview before any detail."))
L['Process Description & Passive Voice']=page(
 ["read a process diagram and decide whether it is linear or a cycle","use sequence words and the present passive to describe each stage","write an overview that names the number of stages and the start and end"],
 h("Two kinds of process"),
 table(["Type","What it looks like","How to start"],[
  ["Linear","A start and an end (making cement, producing electricity)","There are eight stages, beginning with ... and ending with ..."],
  ["Cycle","No real start; it repeats (water cycle, life cycle)","The diagram shows a cycle with five stages ..."]]),
 h("Present passive for processes"),
 p("A process is described in the <strong>present passive</strong> because the action matters, not who does it: <em>The clay <strong>is heated</strong> and then <strong>is mixed</strong> with water.</em> Use the active only when a natural thing does the action: <em>The water <strong>evaporates</strong>.</em>"),
 h("Sequence words"),
 table(["Stage","Words"],[["Start","First, To begin with, The process begins when ..."],["Middle","Next, Then, After that, Following this, Once this has been done"],["Overlap","While this is happening, At the same time, Meanwhile"],["End","Finally, In the last stage, The process ends with ..."]]),
 warn("Do not use <em>First, second, third</em> for every stage. It sounds like a list. Vary the words and combine two stages in one sentence with <em>which, after which, before</em>."),
 h("Structure"),
 ol(["<strong>Introduction:</strong> what the diagram shows.","<strong>Overview:</strong> the number of main stages and the start and end products.","<strong>Detail:</strong> two paragraphs following the order of the diagram."]),
 ex("Model overview","<p>Overall, the production of bricks involves six stages, from digging clay to delivering the finished bricks to customers.</p>"),
 tryit("Turn each into a passive sentence.",["Workers dig the clay from the ground.","A machine crushes the clay.","They fire the bricks in a kiln."],["The clay is dug from the ground.","The clay is crushed by a machine (or: The clay is crushed).","The bricks are fired in a kiln."]),
 take("Decide linear or cycle, describe each stage in the present passive, vary your sequence words, and state the number of stages in your overview."))
L['Task 1 Report Structuring']=page(
 ["build a Task 1 report from four clear paragraphs","write an overview that earns the higher bands","decide what to include and what to leave out"],
 h("The four-paragraph report"),
 table(["Paragraph","Job","Length"],[["1 Introduction","Paraphrase what the visual shows","1–2 sentences"],["2 Overview","The two or three main features, with no detailed numbers","2–3 sentences"],["3 Detail 1","One group of data, with evidence and comparison","3–4 sentences"],["4 Detail 2","The other group of data","3–4 sentences"]]),
 h("Writing the overview"),
 p("The overview is the most important paragraph in Task 1. Look for: the <strong>highest</strong> and <strong>lowest</strong>, the <strong>biggest change</strong>, the <strong>overall trend</strong>, and any <strong>striking similarity or difference</strong>."),
 ex("Weak and strong","<p><strong>Weak (details, not an overview):</strong> In 2010, 40% of people used cars.</p><p><strong>Strong:</strong> Overall, car use grew steadily, while bus and train use fell, and cars remained the most popular option throughout.</p>"),
 h("Choosing what to include"),
 ul(["Select the key features. You do not have to report every number.","Group data that behave alike (the three rising lines together).","Always include units (%, million, tonnes) and years.","Never explain <em>why</em>."]),
 h("A template you can adapt"),
 p("<em>The [chart] illustrates [what] in [where] [when]. Overall, [main trend 1], while [main trend 2]. [Group A] ... [figures and comparison]. In contrast, [Group B] ... [figures and comparison].</em>"),
 tryit("Use these notes to write an overview (two sentences, no figures): coffee sales 20 → 45 million over 10 years; tea sales 30 → 28 million; coffee overtook tea in year 6.",[],["Overall, coffee sales more than doubled while tea sales stayed almost flat. Coffee overtook tea part-way through the period and ended well ahead."]),
 warn("If you run short of time, write the introduction and overview first and one detail paragraph. A report with no overview cannot score above band 5 for Task Achievement."),
 take("Introduction, overview, two detail paragraphs. Spend your best effort on the overview: it shows the examiner you understand the whole picture."))

LESSONS = L
