from lib import *
L={}
L['Mock 1 Review']=page(
 ["turn a mock result into a short list of things to fix","sort every lost mark into a cause, not just a question number","write three specific goals for the next fortnight"],
 h("A result is data, not a verdict"),
 p("Your mock gave you a band for each skill. That number tells you where you are. The <strong>errors</strong> tell you what to do next. Do not skip this lesson: learners who review a mock properly improve much faster than learners who take more mocks."),
 h("Step 1: build an error log"),
 p("For Listening and Reading, list every wrong or blank answer and give it one cause:"),
 table(["Cause","What it looks like","Fix"],[
  ["Vocabulary","You did not know a word in the text or the question","Add it to your word list with a sentence"],
  ["Misread the task","You wrote two words when the limit was one; you missed 'NOT'","Underline the instruction before you start"],
  ["Ran out of time","The last 5-8 questions are blank or guessed","See the time-management lesson that follows"],
  ["Spelling / grammar","Right idea, marked wrong: 'enviroment', 'child' for 'children'","Check singular/plural and spelling in every answer"],
  ["Distractor","The speaker corrected themselves; you wrote the first answer","Listen to the end of each section of the recording"],
  ["Inference too far","True/False/Not Given: you decided from what you think, not what the text says","Use only the text"]]),
 h("Step 2: check Writing with the four criteria"),
 p("Reread each Writing task. Give yourself a tick or a cross for each of these, then mark the weakest criterion:"),
 ul(["Did I answer every part of the question (Task 1: a clear overview)?","Is each paragraph about one idea, with clear linking?","Did I use a range of vocabulary and avoid repeating the same word?","Did I use some complex sentences, and are most sentences free of errors?"]),
 h("Step 3: Speaking"),
 p("If you recorded yourself, listen once for <strong>fluency</strong> (pauses, repeating), once for <strong>vocabulary</strong> (did you say 'good' ten times?) and once for <strong>pronunciation</strong> (words you were unsure of)."),
 h("Step 4: three goals"),
 p("Write three goals that are specific and measurable. Not <em>Improve reading</em>, but <em>Do one True/False/Not Given set every day and reach 80% by Sunday</em>."),
 tip("Keep the error log going all course. Patterns show up after three or four entries."),
 take("Sort mistakes by cause, fix the cause, and turn the results into three specific goals."))
L['Reading Time-Management']=page(
 ["divide the 60 minutes so all 40 questions get an attempt","skim and scan efficiently","decide when to move on and when to guess"],
 h("The 60-minute problem"),
 p("Reading has three passages, 40 questions and <strong>no extra time to transfer answers</strong>. Most lost marks in Reading come from time, not knowledge. The aim is 20 minutes per passage, and slightly less on Passage 1 so you can spend a little more on Passage 3."),
 h("Three tools"),
 ol(["<strong>Skim</strong> (about one minute): read the title, the first sentence of each paragraph and the last sentence of the passage to see the shape of the text.","<strong>Scan</strong>: look for a specific name, number, date or key word without reading everything.","<strong>Read closely</strong>: only the paragraph the question points to."]),
 h("Plan for each passage"),
 table(["Minutes","What to do"],[["0-1","Skim the passage for its structure"],["1-2","Read the instructions and questions of the first group"],["2-15","Answer in the order of the questions, scanning the text for keywords"],["15-19","Second group of questions"],["19-20","Check spelling and word limits; transfer is direct in Reading, so write final answers as you go"]]),
 h("Order of attack"),
 ul(["Questions with a keyword you can find quickly (names, numbers, dates) are quick marks; do them first.","<strong>Matching headings</strong> need the whole passage; do them after you have skimmed it.","<strong>True/False/Not Given</strong> and Yes/No/Not Given need close reading; leave them until you have the quick marks."]),
 warn("Never leave a question blank. There is no penalty for a wrong answer. If you are stuck for more than a minute, guess and mark the question to come back to."),
 tryit("Practise with a timer this week: one passage, 17 minutes, no dictionary.",["Note the time you finish the first question group.","Mark any question you guessed.","After the timer, look at how many of the guesses were right."],None),
 take("Three passages, twenty minutes each. Skim first, answer the quick marks first, and never leave a blank."))
L['Speaking Part 2 Drilling']=page(
 ["use the one minute of preparation to plan four points","speak for a full one to two minutes without a long silence","use tenses and linking words that show range"],
 h("What happens in Part 2"),
 p("The examiner gives you a task card with a topic and four prompts. You have <strong>one minute</strong> to prepare (you may write notes) and then speak for <strong>one to two minutes</strong>. The examiner may ask one or two short questions after."),
 ex("A task card","<p><strong>Describe a book that you enjoyed reading.</strong></p><p>You should say: what the book was, who wrote it, what it was about, and explain why you enjoyed it.</p>"),
 h("Your one-minute plan"),
 p("Do not write sentences. Write <strong>one keyword for each prompt</strong>, plus one extra detail or example for each."),
 table(["Prompt","Keyword","Extra detail"],[["What the book was","'The Alchemist'","read at 17, a gift"],["Who wrote it","Paulo Coelho","Brazilian; my sister told me"],["What it was about","shepherd, dreams","travel to Egypt"],["Why I enjoyed it","hope, simple","reread it after exams"]]),
 h("How to fill two minutes"),
 ul(["Answer each prompt with <strong>two or three sentences</strong>, not one.","Give one <strong>example or short story</strong>: a real moment is easier to talk about than an opinion.","Use a mixture of tenses: past (what happened), present (what it means to you now), and, if you can, future or conditional (<em>I'd love to read it again</em>).","If you run out of ideas, go back to the last prompt: <em>Why did I enjoy it? Because ...</em>"]),
 h("Linking phrases that help you keep going"),
 p("<em>To begin with ... / What I remember most is ... / The reason for that is ... / On top of that ... / Looking back ... / To sum up ...</em>"),
 warn("Do not memorise a whole answer. Examiners recognise a rehearsed answer and it can lower your fluency score. Memorise <strong>structures and phrases</strong>, not stories."),
 h("Drill routine (15 minutes, 4 days a week)"),
 ol(["Pick a random topic (a person, a place, an object, an event).","Take exactly one minute to plan.","Speak for two minutes, recorded on your phone.","Listen back once: mark where you paused or repeated a word.","Redo it once, fixing only those points."]),
 take("Plan four keywords, tell a small story, mix your tenses, and never stop for more than two or three seconds. Two minutes is longer than you think."))
L['Speaking Part 3 Drilling']=page(
 ["give extended, reasoned answers to abstract questions","use a simple structure to organise a spoken answer","compare past and present, and speak about society, not only yourself"],
 h("What is different in Part 3"),
 p("Part 3 is a discussion of about four to five minutes. The questions are more <strong>abstract</strong> and connected to the Part 2 topic: not <em>Did you enjoy the book?</em> but <em>Do you think people read less than in the past?</em> The examiner wants opinions, reasons and comparisons, in longer answers."),
 h("A simple answer structure (PEE)"),
 ol(["<strong>Point:</strong> answer the question directly.","<strong>Explain:</strong> say why, or give the reason.","<strong>Example:</strong> a short example from your life, a friend or your country."]),
 ex("Question and answer","<p><em>Do you think people read less than in the past?</em></p><p><strong>P</strong> I think they probably do, at least books. <strong>E</strong> The main reason is that screens compete for people's free time. <strong>E</strong> For example, most of my friends read news on their phones but only a few read a novel each month.</p>"),
 h("Useful language"),
 table(["To do this","Say"],[["Give an opinion","In my view / As far as I'm concerned / I tend to think"],["Be careful (hedging)","It depends on ... / Generally speaking / to some extent"],["Compare past and present","Years ago ... whereas nowadays ..."],["Talk about society","Many people ... / Younger people tend to ..."],["Buy thinking time","That's an interesting question. Let me think for a moment."]]),
 warn("Do not answer with one sentence, and do not just say 'I don't know'. If you have no strong view, say what people <em>might</em> think and why."),
 tryit("Answer each question aloud in 30-40 seconds using Point, Explain, Example.",["Why do some people prefer to live in a big city?","How has technology changed the way we communicate?","Should children be taught to manage money at school?"],None),
 take("Point, explanation, example. Talk about people in general, compare past and present, and keep your answers to about half a minute."))
L['Listening Fast-Audio Drills']=page(
 ["follow fast, natural speech in Sections 3 and 4","predict what you will hear from the questions","avoid the spelling and distractor mistakes that cost easy marks"],
 h("Why speed matters"),
 p("In the real test you hear each recording once, at natural speed, and Section 4 is a lecture with no pauses. Listening practice at slower speed does not prepare you for this. The drills below train your ear for fast speech."),
 h("Before the recording: predict"),
 ul(["In the 30 seconds you get, read the questions and <strong>underline the key words</strong>.","Decide what <em>kind</em> of answer is needed: a number, a name, a place, an adjective?","Look for words that will be paraphrased: <em>increase</em> may be heard as <em>go up</em>."]),
 h("During: listen for signposts"),
 table(["The speaker says","It usually means"],[["However / But / Actually","The first idea is being corrected; the answer comes next"],["First of all / Next / Finally","A list or order of information"],["The main reason is ...","Key information follows"],["In other words / That is to say","A repeat in simpler words"]]),
 warn("<strong>Distractors.</strong> A speaker often gives a wrong option first and then corrects it: <em>The meeting is on Tuesday. Oh, no, sorry, Wednesday.</em> Write the final answer only."),
 h("Fast-audio drills (four days a week, 20 minutes)"),
 ol(["<strong>Shadowing:</strong> play 30 seconds of a lecture and repeat aloud, just behind the speaker.","<strong>Dictation at 1.25x speed:</strong> play a short clip at 1.25x speed, write what you hear, then check against the transcript.","<strong>Number and name drill:</strong> listen for numbers, dates, prices and spelled-out names; write only those.","<strong>Gist:</strong> after a whole section, say aloud in one sentence what it was about."]),
 h("Easy marks you must not lose"),
 ul(["Spelling: the answer must be spelled correctly. Practise common words (environment, government, temperature).","Plural: <em>student</em> and <em>students</em> are different answers.","Word limit: 'ONE WORD ONLY' means one word."]),
 take("Predict from the questions, listen for signposts and corrections, and train your ear on fast audio with shadowing and dictation."))
L['Complex Passage Strategy']=page(
 ["map a dense passage quickly, paragraph by paragraph","match headings and identify True/False/Not Given accurately","work out unknown words from context rather than stopping"],
 h("Paragraph mapping"),
 p("For every long passage, spend a minute writing a <strong>five-word label</strong> beside each paragraph. It is a map: when a question names an idea, you know where to look."),
 ex("Example labels","<p>Para A: history of the method. Para B: two main problems. Para C: a case study. Para D: expert criticism. Para E: future outlook.</p>"),
 h("Matching headings"),
 ul(["Read the <strong>first and last sentence</strong> of the paragraph; the main idea is usually there.","Cross out headings you have used.","Beware of headings that share a word with the paragraph but describe a different idea."]),
 h("True / False / Not Given"),
 table(["Answer","The rule"],[["True","The text says the same thing in other words"],["False","The text says the opposite"],["Not Given","The text does not say, however likely the statement seems"]]),
 warn("Not Given is the biggest trap. If you must use your own knowledge to decide, it is probably Not Given."),
 h("Unknown words"),
 p("You do not need to understand every word. Ask: is it a noun, verb or adjective? Is the tone positive or negative? Does the next sentence explain it? Move on if the question does not depend on it."),
 tryit("Read the paragraph beginning of any reading passage and write a five-word label for each of the first three paragraphs. Compare with the text's own headings.",[],None),
 take("Label every paragraph, use topic sentences for headings, and judge True/False/Not Given only from the words on the page."))
L['Final Self-Assessment']=page(
 ["judge your level in each skill honestly","name the three things that will most raise your score","build a simple plan for the final days before the test"],
 h("Rate yourself against the descriptors"),
 p("For each row, give yourself a score from 1 (rarely) to 4 (almost always). Be strict."),
 table(["Skill","Question","1-4"],[
  ["Listening","I can follow a whole lecture and write answers without missing the next question",""],
  ["Listening","I check spelling and singular/plural in every answer",""],
  ["Reading","I finish all 40 questions in 60 minutes",""],
  ["Reading","I get True/False/Not Given right most of the time",""],
  ["Writing 1","I always write a clear overview",""],
  ["Writing 2","Each paragraph has one main idea with an example",""],
  ["Speaking","I can speak for two minutes on Part 2 without long pauses",""],
  ["Speaking","I use a range of vocabulary, not the same few words",""]]),
 h("Choose three priorities"),
 p("Look at your lowest scores. Choose the <strong>three</strong> that are also worth the most: a Task 2 problem is worth twice a Task 1 problem; a time problem in Reading affects 10 questions at once."),
 h("The last week"),
 ul(["Do not learn new material. Review your error log and your word list.","Take one full timed test and one timed Writing task, and mark them carefully.","Practise Speaking aloud every day, even for five minutes.","Sleep, eat and travel plans: know where the test is and how long it takes to get there."]),
 take("An honest audit beats a hopeful guess. Fix the three biggest gaps, revise instead of cramming, and arrive rested."))
L['Error Review']=page(
 ["find the errors in your own Writing that cost the most marks","correct them and see the pattern","write a short list of your personal top errors"],
 h("Why review your own writing"),
 p("Everyone has a small set of mistakes that keep appearing. Finding <em>yours</em> is more useful than studying a long list of general rules."),
 h("The seven most common errors"),
 table(["Error","Example","Correct"],[
  ["Articles","Government should build a school.","The government should build a school."],
  ["Subject-verb agreement","The number of cars are rising.","The number of cars is rising."],
  ["Singular / plural","Many student prefer ...","Many students prefer ..."],
  ["Tense","Last year sales increase.","Last year sales increased."],
  ["Prepositions","depend of, interested about","depend on, interested in"],
  ["Run-on sentences","Cars are popular, they are cheap.","Cars are popular because they are cheap."],
  ["Word form","a big different","a big difference"]]),
 h("Review method"),
 ol(["Reread your Writing Test 3 answer slowly, aloud if you can.","Underline each error and write the type in the margin.","Rewrite the sentence correctly.","Count the errors by type. The largest type is your priority."]),
 tryit("Correct these sentences.",["The graph show a increase in sale.","A lot of peoples think that education are important.","In the recent years, many students goes abroad."],["The graph shows an increase in sales.","A lot of people think that education is important.","In recent years, many students have gone abroad."]),
 take("Know your top three personal errors and check for them in every final read-through."))
L['Mock 2 Review']=page(
 ["compare Mock 2 with Mock 1 to see what has really improved","find the errors that remain","decide what to change in your test strategy"],
 h("Compare, do not just score"),
 p("Put your Mock 1 and Mock 2 results side by side. For each skill, note the band, then the <strong>cause</strong> of each lost mark using the same error log as last time. What went down? What went up? What is the same?"),
 table(["","Mock 1","Mock 2","Change"],[["Listening","","",""],["Reading","","",""],["Writing 1 / 2","","",""],["Speaking","","",""],["Timing problems","","",""]]),
 h("Questions to ask"),
 ul(["Which error type has shrunk? Keep doing what worked.","Which error type has not moved? That is where the time should go next.","Did I run out of time in the same place? If so, change the plan, not the effort."]),
 take("The point of two mocks is the comparison. Repeat what improved, and attack whatever did not move."))
L['Strategy Adjustments']=page(
 ["turn the mock review into specific changes to your test plan","set time limits for each part of the test","decide what you will do when you are stuck"],
 h("From review to rules"),
 p("Write three rules for yourself, based on your mock. Rules are short and start with a verb."),
 ex("Example rules","<p>1. In Reading, leave any question after one minute and come back.</p><p>2. In Task 2, write a two-minute plan before the first sentence.</p><p>3. In Speaking Part 2, use all sixty seconds to write four keywords.</p>"),
 h("A time budget you can rehearse"),
 table(["Part","Budget"],[["Listening","use the prep time to underline keywords; check spelling at the end"],["Reading","20-20-20; blank answers not allowed"],["Writing","Task 1: 20 (5 plan+write, 3 check); Task 2: 40 (5 plan, 30 write, 5 check)"],["Speaking","aim for full-length answers in every part"]]),
 h("When you are stuck"),
 ul(["Listening: write a guess and move on; missing the next answer costs more.","Reading: skip and return; guess at the end.","Writing: if you have no idea, take a clear position and use the ideas you can explain best.","Speaking: rephrase the question to buy time, or say 'Let me think for a second'."]),
 take("Turn your mock lessons into three rules and a time budget, and rehearse them in your next practice."))
L['Advanced Listening']=page(
 ["handle Section 3 and Section 4 (academic discussion and lecture) with confidence","follow a discussion between several speakers","label maps and plans and complete flow-charts"],
 h("What is harder in Sections 3 and 4"),
 ul(["Section 3 has two to four speakers, often students and a tutor, and they <strong>disagree or change their minds</strong>.","Section 4 is a monologue with no break and academic vocabulary.","Answers are often a paraphrase, not the words you heard."]),
 h("Multiple speakers"),
 p("Note who holds which opinion as you listen: draw a small table of the speakers' names with a word for each opinion. Questions often ask who said what."),
 h("Labelling a map or plan"),
 p("Before the recording, look at the layout and find fixed points (entrance, river, north arrow). Learn direction words: <em>opposite, beside, next to, behind, on the left, to the north of</em>. The speaker will move around the plan in order."),
 h("Flow-chart and note completion"),
 p("The gaps come in the order of the recording. Use the words before and after each gap to predict its type (noun, verb, number). Keep to the word limit."),
 tryit("Practise this week with a Section 4 lecture. After each two minutes pause and write, in six words, the lecturer's main point so far.",[],None),
 take("Follow who says what, use the order of the recording, and expect paraphrase."))
L['Advanced Reading']=page(
 ["tackle summary completion, matching information and matching features","use the writer's viewpoint questions correctly","read faster without losing accuracy"],
 h("The harder question types"),
 table(["Type","What to do"],[["Matching information","Find which paragraph contains the detail; not every paragraph is used, and one may be used twice"],["Matching features","Match statements to people or groups; scan for names first"],["Summary completion (word bank)","Predict the part of speech, then match the closest meaning"],["Yes / No / Not Given","Concerns the writer's opinion, not facts; look for words like 'believes', 'argues', 'suggests'"]]),
 h("Reading for the writer's view"),
 p("Opinions are signalled by adjectives (<em>unfortunate, encouraging</em>), reporting verbs (<em>claim, argue, suggest</em>) and modal verbs (<em>may, should</em>). A writer who <em>reports</em> an opinion is not necessarily <em>sharing</em> it."),
 h("Working faster"),
 ul(["Skim the introduction and the conclusion for the writer's position.","Do not read every word of long examples; read the sentence before and after them.","Practise on 700-word texts with a timer and lower it by a minute each week."]),
 take("Know the question type before you read, scan for names and keywords, and separate what a writer reports from what a writer believes."))
L['Advanced Speaking']=page(
 ["raise your fluency and range across all three parts","use more precise vocabulary and a wider range of grammar","improve stress and intonation so you are easy to follow"],
 h("What examiners reward at higher bands"),
 ul(["<strong>Fluency:</strong> you speak at length with few pauses, and hesitation is about ideas, not words.","<strong>Vocabulary:</strong> you use less common words and idiomatic phrases accurately, and paraphrase when you cannot remember a word.","<strong>Grammar:</strong> a mix of simple and complex sentences with most of them correct.","<strong>Pronunciation:</strong> clear sounds, natural stress and rhythm."]),
 h("Range without risk"),
 table(["Do","Example"],[["Use conditionals","If I had more time, I would learn a second instrument."],["Use relative clauses","My brother, who lives in Toronto, ..."],["Use less common words you know well","reliable, exhausting, thought-provoking"],["Paraphrase","It's a sort of tool for measuring ... (when you lack the word)"]]),
 warn("A rare idiom used wrongly costs more than plain vocabulary used correctly. Use only what you can say naturally."),
 h("Stress and intonation"),
 p("English is stress-timed: content words (nouns, main verbs, adjectives) are louder and longer; small words are quick. Your voice should rise and fall, not stay flat. Record yourself reading a short paragraph and listen for that rhythm."),
 take("Aim for extended, natural answers, use a range of structures you control, and let stress and intonation carry your meaning."))
L['Final Writing Polish']=page(
 ["revise a Task 2 essay so that it moves up a band","edit for the four criteria in a systematic order","use the last three minutes of the test well"],
 h("Polish in four passes"),
 ol(["<strong>Task Response:</strong> did I answer every part of the question, with a clear position throughout?","<strong>Coherence and Cohesion:</strong> does each paragraph have one main idea, and is the link between ideas clear (but not mechanical)?","<strong>Vocabulary:</strong> replace repeated words; check collocations (<em>make a decision</em>, not <em>do a decision</em>).","<strong>Grammar:</strong> at least a few complex sentences, all correct; then the top three personal errors."]),
 h("Upgrade one paragraph"),
 ex("Before and after","<p><strong>Before:</strong> Technology is good. It helps people. It makes life easy.</p><p><strong>After:</strong> Technology has transformed daily life by saving time on routine tasks, which allows people to focus on more meaningful work.</p>"),
 h("The last three minutes"),
 ul(["Count your words (250+ for Task 2). Being 5 or 10 over is fine.","Check the introduction and conclusion first; examiners read them carefully.","Fix spelling and plurals, and make sure each sentence has a verb."]),
 take("Revise in an order: response, coherence, vocabulary, grammar. Use the last minutes for the edit that is most likely to be needed."))
L['Consolidation — Targeted Weak-Area Drilling']=page(
 ["choose your weak areas from evidence, not feeling","build a focused 90-minute practice session","measure whether the drilling worked"],
 h("Find the weak areas"),
 p("Use your error log and your last two mocks. List your three lowest-scoring areas, for example <em>Matching headings</em>, <em>Task 1 overview</em>, <em>Speaking fluency</em>. Then rank them by how many marks they cost."),
 h("A 90-minute session"),
 table(["Minutes","Activity"],[["0-10","Warm up: review your error log entries for the target area"],["10-40","Focused drill: 10-15 questions or one short task on the weak area only"],["40-60","Check every answer; write why each error happened"],["60-80","Repeat with a fresh set"],["80-90","Write what you will do differently next time"]]),
 h("Measure it"),
 ul(["Set a target before you start (for example 8/10 correct).","Record the score of every session in a table.","If two sessions do not move the score, change the method: get an explanation, then try again."]),
 take("Drill what the data says is weak, in short focused sessions, and check the score to prove it is working."))
L['Final Review']=page(
 ["run through a last checklist for all four skills","decide what to do in the last 48 hours","enter the test calm and organised"],
 h("Skill by skill checklist"),
 table(["Skill","Checklist"],[["Listening","Underline keywords; check spelling and plurals; stay with the recording"],["Reading","20-20-20; answers in the quick order; never leave a blank"],["Writing 1","Introduction, overview, two detail paragraphs; no opinion"],["Writing 2","Two-minute plan; clear position; one idea per paragraph; check the conclusion"],["Speaking","Full answers; Part 2: four keywords, two minutes; Part 3: point, explain, example"]]),
 h("The last 48 hours"),
 ul(["Review only: error log, word list, model answers.","One short practice per skill, not a full mock.","Prepare your identification, pen and pencil, and the route to the centre."]),
 take("You have practised the skills. Now stay calm, follow your rules and let your preparation show."))
LESSONS = L
